name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore KokoReflection/KokoReflection.csproj
    - name: Build
      run: dotnet build KokoReflection/KokoReflection.csproj --no-restore
    - name: Test
      run: dotnet test KokoReflection/KokoReflection.csproj --no-build --verbosity normal